'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace wsAlmacen
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="wsAlmacen.IwsAlmacen")>  _
    Public Interface IwsAlmacen
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IwsAlmacen/retornaMon", ReplyAction:="http://tempuri.org/IwsAlmacen/retornaMonResponse")>  _
        Function retornaMon() As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IwsAlmacen/retornaMon", ReplyAction:="http://tempuri.org/IwsAlmacen/retornaMonResponse")>  _
        Function retornaMonAsync() As System.Threading.Tasks.Task(Of System.Data.DataTable)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IwsAlmacenChannel
        Inherits wsAlmacen.IwsAlmacen, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class IwsAlmacenClient
        Inherits System.ServiceModel.ClientBase(Of wsAlmacen.IwsAlmacen)
        Implements wsAlmacen.IwsAlmacen
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function retornaMon() As System.Data.DataTable Implements wsAlmacen.IwsAlmacen.retornaMon
            Return MyBase.Channel.retornaMon
        End Function
        
        Public Function retornaMonAsync() As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements wsAlmacen.IwsAlmacen.retornaMonAsync
            Return MyBase.Channel.retornaMonAsync
        End Function
    End Class
End Namespace
