/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finalproyecto;

import java.awt.BorderLayout;

/**
 *
 * @author Sergio Orozco
 */
public class Mathe extends javax.swing.JPanel {

    /**
     * Creates new form Mathe
     */
    public Mathe() {
        initComponents();
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Principalpanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        rSButtonMetro5 = new rsbuttom.RSButtonMetro();
        tantoporciento = new rsbuttom.RSButtonMetro();
        rSButtonMetro6 = new rsbuttom.RSButtonMetro();
        rSButtonMetro19 = new rsbuttom.RSButtonMetro();
        rSButtonMetro7 = new rsbuttom.RSButtonMetro();
        rSButtonMetro20 = new rsbuttom.RSButtonMetro();
        rSButtonMetro8 = new rsbuttom.RSButtonMetro();
        rSButtonMetro21 = new rsbuttom.RSButtonMetro();
        rSButtonMetro9 = new rsbuttom.RSButtonMetro();
        rSButtonMetro22 = new rsbuttom.RSButtonMetro();
        rSButtonMetro23 = new rsbuttom.RSButtonMetro();

        setBackground(new java.awt.Color(51, 153, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Principalpanel.setBackground(new java.awt.Color(0, 204, 255));
        Principalpanel.setRequestFocusEnabled(false);

        jPanel2.setBackground(new java.awt.Color(86, 221, 253));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1643, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout PrincipalpanelLayout = new javax.swing.GroupLayout(Principalpanel);
        Principalpanel.setLayout(PrincipalpanelLayout);
        PrincipalpanelLayout.setHorizontalGroup(
            PrincipalpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        PrincipalpanelLayout.setVerticalGroup(
            PrincipalpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PrincipalpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(939, Short.MAX_VALUE))
        );

        add(Principalpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 1560, 990));

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Palatino Linotype", 3, 24)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/tools.png"))); // NOI18N
        jLabel2.setText("Temas");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 170, 60));

        rSButtonMetro5.setBackground(new java.awt.Color(51, 153, 255));
        rSButtonMetro5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/delete.png"))); // NOI18N
        rSButtonMetro5.setText("Razones Geométricas");
        rSButtonMetro5.setColorNormal(new java.awt.Color(51, 153, 255));
        rSButtonMetro5.setColorPressed(new java.awt.Color(51, 153, 255));
        rSButtonMetro5.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        rSButtonMetro5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rSButtonMetro5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMetro5ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonMetro5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 300, 50));

        tantoporciento.setBackground(new java.awt.Color(51, 153, 255));
        tantoporciento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/delete.png"))); // NOI18N
        tantoporciento.setText("El tanto por ciento");
        tantoporciento.setColorNormal(new java.awt.Color(51, 153, 255));
        tantoporciento.setColorPressed(new java.awt.Color(51, 153, 255));
        tantoporciento.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        tantoporciento.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tantoporciento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tantoporcientoActionPerformed(evt);
            }
        });
        jPanel1.add(tantoporciento, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 300, 50));

        rSButtonMetro6.setBackground(new java.awt.Color(51, 153, 255));
        rSButtonMetro6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/delete.png"))); // NOI18N
        rSButtonMetro6.setText("Regla de tres compuesta");
        rSButtonMetro6.setColorNormal(new java.awt.Color(51, 153, 255));
        rSButtonMetro6.setColorPressed(new java.awt.Color(51, 153, 255));
        rSButtonMetro6.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        rSButtonMetro6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rSButtonMetro6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMetro6ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonMetro6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 300, 50));

        rSButtonMetro19.setBackground(new java.awt.Color(51, 153, 255));
        rSButtonMetro19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/delete.png"))); // NOI18N
        rSButtonMetro19.setText("Interés Simple");
        rSButtonMetro19.setColorNormal(new java.awt.Color(51, 153, 255));
        rSButtonMetro19.setColorPressed(new java.awt.Color(51, 153, 255));
        rSButtonMetro19.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        rSButtonMetro19.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(rSButtonMetro19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 300, 50));

        rSButtonMetro7.setBackground(new java.awt.Color(51, 153, 255));
        rSButtonMetro7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/delete.png"))); // NOI18N
        rSButtonMetro7.setText("Figuras Tridimensionales");
        rSButtonMetro7.setColorNormal(new java.awt.Color(51, 153, 255));
        rSButtonMetro7.setColorPressed(new java.awt.Color(51, 153, 255));
        rSButtonMetro7.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        rSButtonMetro7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rSButtonMetro7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMetro7ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonMetro7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 300, 50));

        rSButtonMetro20.setBackground(new java.awt.Color(51, 153, 255));
        rSButtonMetro20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/delete.png"))); // NOI18N
        rSButtonMetro20.setText("Expresión Algebraica");
        rSButtonMetro20.setColorNormal(new java.awt.Color(51, 153, 255));
        rSButtonMetro20.setColorPressed(new java.awt.Color(51, 153, 255));
        rSButtonMetro20.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        rSButtonMetro20.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(rSButtonMetro20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 300, 50));

        rSButtonMetro8.setBackground(new java.awt.Color(51, 153, 255));
        rSButtonMetro8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/delete.png"))); // NOI18N
        rSButtonMetro8.setText("Grado de un término");
        rSButtonMetro8.setColorNormal(new java.awt.Color(51, 153, 255));
        rSButtonMetro8.setColorPressed(new java.awt.Color(51, 153, 255));
        rSButtonMetro8.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        rSButtonMetro8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rSButtonMetro8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMetro8ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonMetro8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 300, 50));

        rSButtonMetro21.setBackground(new java.awt.Color(51, 153, 255));
        rSButtonMetro21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/delete.png"))); // NOI18N
        rSButtonMetro21.setText("Suma y resta Algebraica");
        rSButtonMetro21.setColorNormal(new java.awt.Color(51, 153, 255));
        rSButtonMetro21.setColorPressed(new java.awt.Color(51, 153, 255));
        rSButtonMetro21.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        rSButtonMetro21.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rSButtonMetro21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMetro21ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonMetro21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 300, 50));

        rSButtonMetro9.setBackground(new java.awt.Color(51, 153, 255));
        rSButtonMetro9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/delete.png"))); // NOI18N
        rSButtonMetro9.setText("Multiplicacion Algebraica");
        rSButtonMetro9.setColorNormal(new java.awt.Color(51, 153, 255));
        rSButtonMetro9.setColorPressed(new java.awt.Color(51, 153, 255));
        rSButtonMetro9.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        rSButtonMetro9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rSButtonMetro9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMetro9ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonMetro9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 300, 50));

        rSButtonMetro22.setBackground(new java.awt.Color(51, 153, 255));
        rSButtonMetro22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/delete.png"))); // NOI18N
        rSButtonMetro22.setText("ARDUINO");
        rSButtonMetro22.setColorNormal(new java.awt.Color(51, 153, 255));
        rSButtonMetro22.setColorPressed(new java.awt.Color(51, 153, 255));
        rSButtonMetro22.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        rSButtonMetro22.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rSButtonMetro22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMetro22ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonMetro22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 300, 50));

        rSButtonMetro23.setBackground(new java.awt.Color(51, 153, 255));
        rSButtonMetro23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/delete.png"))); // NOI18N
        rSButtonMetro23.setText("División Algebraica");
        rSButtonMetro23.setColorNormal(new java.awt.Color(51, 153, 255));
        rSButtonMetro23.setColorPressed(new java.awt.Color(51, 153, 255));
        rSButtonMetro23.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        rSButtonMetro23.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(rSButtonMetro23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 300, 50));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 11, 310, 866));
    }// </editor-fold>//GEN-END:initComponents

    private void rSButtonMetro5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetro5ActionPerformed
     
   

    }//GEN-LAST:event_rSButtonMetro5ActionPerformed

    private void rSButtonMetro6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetro6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonMetro6ActionPerformed

    private void rSButtonMetro7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetro7ActionPerformed
        primerbmate p=new primerbmate();
        p.setSize(1720, 1080);
        p.setLocation(15,0);
        Principalpanel.removeAll();
        Principalpanel.add(p,BorderLayout.CENTER);
        Principalpanel.revalidate();
        Principalpanel.repaint();
        
    }//GEN-LAST:event_rSButtonMetro7ActionPerformed

    private void rSButtonMetro8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetro8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonMetro8ActionPerformed

    private void rSButtonMetro9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetro9ActionPerformed
        multialgebra tt=new multialgebra();
        tt.setSize(1643, 990);
        tt.setLocation(15,0);
        Principalpanel.removeAll();
        Principalpanel.add(tt,BorderLayout.CENTER);
        Principalpanel.revalidate();
        Principalpanel.repaint();
    }//GEN-LAST:event_rSButtonMetro9ActionPerformed

    private void tantoporcientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tantoporcientoActionPerformed
        Tantoporciento tt=new Tantoporciento();
        tt.setSize(1643, 990);
        tt.setLocation(15,0);
        Principalpanel.removeAll();
        Principalpanel.add(tt,BorderLayout.CENTER);
        Principalpanel.revalidate();
        Principalpanel.repaint();
    }//GEN-LAST:event_tantoporcientoActionPerformed

    private void rSButtonMetro21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetro21ActionPerformed
       sumayresta p=new sumayresta();
        p.setSize(1643, 990);
        p.setLocation(15,0);
        Principalpanel.removeAll();
        Principalpanel.add(p,BorderLayout.CENTER);
        Principalpanel.revalidate();
        Principalpanel.repaint();
        
    }//GEN-LAST:event_rSButtonMetro21ActionPerformed

    private void rSButtonMetro22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetro22ActionPerformed
       arduino p=new arduino();
        p.setSize(1643, 990);
        p.setLocation(15,0);
        Principalpanel.removeAll();
        Principalpanel.add(p,BorderLayout.CENTER);
        Principalpanel.revalidate();
        Principalpanel.repaint();
    }//GEN-LAST:event_rSButtonMetro22ActionPerformed

    public static void main(String []args){
     
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JPanel Principalpanel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private rsbuttom.RSButtonMetro rSButtonMetro19;
    private rsbuttom.RSButtonMetro rSButtonMetro20;
    private rsbuttom.RSButtonMetro rSButtonMetro21;
    private rsbuttom.RSButtonMetro rSButtonMetro22;
    private rsbuttom.RSButtonMetro rSButtonMetro23;
    private rsbuttom.RSButtonMetro rSButtonMetro5;
    private rsbuttom.RSButtonMetro rSButtonMetro6;
    private rsbuttom.RSButtonMetro rSButtonMetro7;
    private rsbuttom.RSButtonMetro rSButtonMetro8;
    private rsbuttom.RSButtonMetro rSButtonMetro9;
    private rsbuttom.RSButtonMetro tantoporciento;
    // End of variables declaration//GEN-END:variables
}
