/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finalproyecto;

import static finalproyecto.Mathe.Principalpanel;
import java.awt.BorderLayout;

/**
 *
 * @author Sergio Orozco
 */
public class sumayresta extends javax.swing.JPanel {

    /**
     * Creates new form sumayresta
     */
    public sumayresta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 230, 225));

        jLabel1.setFont(new java.awt.Font("Palatino Linotype", 1, 24)); // NOI18N
        jLabel1.setText("Suma y Resta de expresiones algebraicas");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 864, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 856, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1720, 60));

        jLabel2.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        jLabel2.setText("<html>Para sumar y restar Expresiones Algebraicas, lo que se debe hacer es agrupar los términos semejantes y reducirlos tal como ya se estudió anteriormente, y finalmente se unen (juntan) los resultados separados por su respectivo signo.<p>Ejemplo:<pre>        1.     7a - 8b + 5c - 7a + 5a - 6b - 8a + 12b</pre><p><p>Primer paso se separan los términos que son semejantes entre sí:<pre>                7a - 7a + 5a - 8a</pre><p><pre>              - 8b - 6b + 12b</pre><p><pre>                      5c</pre><p><p>Segundo paso se reducen los términos semejantes a uno solo tal como ya se estudió.<pre>         7a - 7a + 5a – 8a = - 3a</pre><p><pre>           - 8b - 6b + 12b = 10b</pre><p><pre>               5c = 5c</pre><p>Finalmente se agrupan los resultados parciales obtenidos en cada operación y esa es nuestra respuesta final.<p><pre>                   -3a + 10b – 5c</pre><p><pre><b>                 ¡Recuerde que únicamente pueden sumarse y/o restarse entre sí los términos semejantes!</b></pre><html>");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1130, 810));

        jButton1.setText("Ejemplos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 650, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         sumyresejemplo p=new sumyresejemplo();
        p.setSize(1643, 990);
        p.setLocation(15,0);
        Principalpanel.removeAll();
        Principalpanel.add(p,BorderLayout.CENTER);
        Principalpanel.revalidate();
        Principalpanel.repaint();
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
