/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finalproyecto;

/**
 *
 * @author Sergio Orozco
 */
public class sumyresejercicio extends javax.swing.JPanel {

    /**
     * Creates new form sumyresejercicio
     */
    public sumyresejercicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 230, 225));

        jLabel1.setFont(new java.awt.Font("Palatino Linotype", 1, 24)); // NOI18N
        jLabel1.setText("Ejercicios de sumas y restas algebraicas");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 878, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 762, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1640, -1));

        jLabel2.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        jLabel2.setText("<html><pre>        1.   3m - 7n + 5m - 7n + 5n + 3n - 8p - 5n + 8p</pre><p><pre>        2.   4p - 7q + 5p - 12p - 11q + 8p - 11q + 12r + p + 5r =</pre><p><pre>        3.   2a2  + 3b2 - 5a2 - 12 b2 - 7a2 + 6b2 - 8a2 - 5 b2 =</pre><p><pre>        4.    7a -  18 b + 5 c - 72a + 5a - 61b - 8a + 12b  =</pre><p><pre>        5.    8a  + 52 b  - 71a + 64 b + 9a - 43b + 7b - 3a =</pre><p><pre>        6.    5a - 3b + c + ( 4a - 5b - c ) =</pre><p><pre>        7.    8x - ( 15y + 16z - 12x ) - ( -13x + 20y ) - ( x + y + z ) =</pre><p><pre>        8.     9x + 13 y - 9z - 7x – ( -y + 2z - ( 5x - 9y + 5z) - 3z ) = </pre><p><pre>        9.    -( x - 2y )  - (3x - ( 2y - z ) - 4x - ( 3y - 2z ) =</pre><p><pre>        10.   6a – (7ab + b - 3ac) + 3bc - c - (8a + 9ab - 4b) - (-5ac + 2bc - 3c)</pre> <html>");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1250, 830));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
