/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finalproyecto;

import static finalproyecto.Mathe.Principalpanel;
import java.awt.BorderLayout;

/**
 *
 * @author Sergio Orozco
 */
public class tantoporcientoejemplo extends javax.swing.JPanel {

    /**
     * Creates new form tantoporcientoejemplo
     */
    public tantoporcientoejemplo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        jLabel2.setText("<html>El licenciado Juan Rojas imparte clases de sociología a 90 alumnos,<p>de ellos 40 perdieron el curso, ¿Qué porcentaje de alumnos<p>perdieron?<p><pre>     90 ________________ 100%</pre><p><pre>     40 ________________    x</pre><p>(40 x 100)/90 = 4000/90 = 44.44<p>La respuesta es: Al Licenciado Rojas le perdió el curso el 44% de los<p>alumnos.  (En esta respuesta se realizo una aproximación) <html>");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 590, 290));

        jLabel4.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        jLabel4.setText("<html>Encontrar el 11.5% de 500<p><pre>100% _______________500</pre><p><pre>11.5% _______________ x </pre><p><p>(11.5 x 500)/100  = 5750/100 = 57.50<p>La respuesta es el 11.5% de 500 es 57.50 <html>");
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 60, 340, 280));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/income.png"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 590, 150, 150));

        jPanel1.setBackground(new java.awt.Color(153, 230, 225));

        jLabel1.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        jLabel1.setText("Ejemplos del tanto por ciento");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1014, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1640, 50));

        jButton1.setText("Ejercicios");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 950, -1, -1));

        jLabel10.setText("<html>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<html>");
        jLabel10.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 50, 20, 320));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 350, 1640, 20));

        jLabel11.setText("<html>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<html>");
        jLabel11.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 360, 20, 620));

        jLabel7.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        jLabel7.setText("<html>En la misión Asambleas de Dios existen 15,000 pastores de ellos<p>únicamente 450 poseen vehículo, ¿Qué porcentaje representan?<p><pre>     15000 ________________ 100%</pre><p><pre>     450 ________________    x</pre><p><p>(450 x 100)/15000 = 45000/15000 = 3<p>La respuesta es: en la misión Asambleas de Dios<p>únicamente el 3% de los pastores posee vehículo.<html>");
        jLabel7.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 60, 530, 290));

        jLabel5.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        jLabel5.setText("<html>También puede suceder que lo que tengamos que encontrar sea el 100%, es decir la cantidad<p>total de donde salió un porcentaje, por ejemplo si una persona dice que tuvo que pagar el<p>25% en de anticipo por la compra de un automóvil y únicamente sabemos que el dinero pagado<p>fue 2,000 quetzales, y queremos saber cuál es la cantidad total que cuesta el vehículo, entonces<p>procedemos de la siguiente forma:<p><pre>     25% ________________ 2000</pre><p><pre>     100% ________________    x</pre><p>Simplemente cambiamos el planteamiento del problema, en la parte de arriba de la regla<p>de tres colocamos el dato conocido que es que 25% es 2000 y el 100% que es el dato que desconocemos<p>lo colocamos en la parte de abajo.Como la regla de tres es directa procedemos de la manera que ya<p>conocemos.<p><p><pre>     25% ________________ 2000</pre><p><pre>     100% ________________    x</pre><p>  (100 x 2000)/25  = 200000/25 = 8000 La respuesta es: el costo total del vehículo es 8000 quetzales<html>");
        jLabel5.setToolTipText("");
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 950, 510));

        jLabel12.setText("<html>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<html>");
        jLabel12.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 50, 20, 290));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Tantoporejercicio p=new Tantoporejercicio();
        p.setSize(1643, 990);
        p.setLocation(15,0);
        Principalpanel.removeAll();
        Principalpanel.add(p,BorderLayout.CENTER);
        Principalpanel.revalidate();
        Principalpanel.repaint();
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
