/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finalproyecto;

/**
 *
 * @author Sergio Orozco
 */
public class Tantoporejercicio extends javax.swing.JPanel {

    /**
     * Creates new form Tantoporejercicio
     */
    public Tantoporejercicio() {
        initComponents();
        a.setVisible(false);
        b.setVisible(false);
        c.setVisible(false);
        d.setVisible(false);
        e.setVisible(false);
        f.setVisible(false);
        g.setVisible(false);
        h.setVisible(false);
        i.setVisible(false);
        j.setVisible(false);
        k.setVisible(false);
        l.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        a = new javax.swing.JLabel();
        b = new javax.swing.JLabel();
        c = new javax.swing.JLabel();
        d = new javax.swing.JLabel();
        e = new javax.swing.JLabel();
        f = new javax.swing.JLabel();
        g = new javax.swing.JLabel();
        h = new javax.swing.JLabel();
        i = new javax.swing.JLabel();
        j = new javax.swing.JLabel();
        k = new javax.swing.JLabel();
        l = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(51, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 230, 225));

        jLabel1.setText("Ejercicios de tanto por ciento");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1643, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        jLabel2.setText("A continuación resuelva los siguientes ejercicios:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 57, 436, -1));

        jLabel3.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        jLabel3.setText("1. Encuentre el 12% de descuento por un artículo que vale Q 5400");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 101, -1, -1));

        jLabel4.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        jLabel4.setText("2. Encuentre el 35% de páginas leídas de un libro de 380 páginas");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jLabel5.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        jLabel5.setText("3. ¿A cómo hay que vender lo que ha costado Q. 680 para ganar el 15% de la venta? ");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        jLabel6.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        jLabel6.setText("<html>4. Un hombre al morir dispone que sus ahorros consistentes en 20.000 dólares, se <p>reparta en 35% a su hermano mayor, el 40% del resto a su hermano menor y lo<p>restante a su ahijado. ¿Cuántos dólares le correspondió a cada uno?<html>");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 530, 70));

        jLabel7.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        jLabel7.setText("4. ¿Cuánto minutos son el 35% de una hora? ");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, -1));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 1210, 10));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 168, 1210, -1));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 1210, 10));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 1220, 10));

        jLabel8.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        jLabel8.setText("5) 7%   de   45");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, -1, -1));

        jLabel9.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        jLabel9.setText("6) 6%   de   68 ");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, -1, -1));

        jLabel10.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        jLabel10.setText("7) 79%   de   135 ");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, -1, -1));

        jLabel11.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        jLabel11.setText("8) 58%   de   111 ");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 530, -1, -1));

        jLabel12.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        jLabel12.setText("9) 1%   de   26126 ");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 570, -1, -1));

        jLabel13.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        jLabel13.setText("10) 58%   de   63 ");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 610, -1, -1));

        jButton1.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        jButton1.setText("Mostrar respuestas");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 580, -1, -1));

        a.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        a.setText("Q648.00");
        add(a, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 100, -1, -1));

        b.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        b.setText("Q133.00");
        add(b, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 140, -1, -1));

        c.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        c.setText("Q782.00");
        add(c, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 220, -1, -1));

        d.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        d.setText("Mayor Q7000.00");
        add(d, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 280, -1, -1));

        e.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        e.setText("Menor Q8000.00");
        add(e, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 320, -1, -1));

        f.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        f.setText("Ahijado Q5000.00");
        add(f, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 280, -1, -1));

        g.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        g.setText("3.5");
        add(g, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 410, -1, -1));

        h.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        h.setText("4.08");
        add(h, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 450, -1, -1));

        i.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        i.setText("106.65");
        add(i, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 490, -1, -1));

        j.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        j.setText("64.38");
        add(j, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 530, -1, -1));

        k.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        k.setText("261.26");
        add(k, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 570, -1, -1));

        l.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        l.setText("36.54");
        add(l, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 610, -1, -1));

        jLabel14.setText("GAY");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 520, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         a.setVisible(true);
        b.setVisible(true);
        c.setVisible(true);
        d.setVisible(true);
        e.setVisible(true);
        f.setVisible(true);
        g.setVisible(true);
        h.setVisible(true);
        i.setVisible(true);
        j.setVisible(true);
        k.setVisible(true);
        l.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel a;
    private javax.swing.JLabel b;
    private javax.swing.JLabel c;
    private javax.swing.JLabel d;
    private javax.swing.JLabel e;
    private javax.swing.JLabel f;
    private javax.swing.JLabel g;
    private javax.swing.JLabel h;
    private javax.swing.JLabel i;
    private javax.swing.JLabel j;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel k;
    private javax.swing.JLabel l;
    // End of variables declaration//GEN-END:variables
}
