/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finalproyecto;

/**
 *
 * @author Sergio Orozco
 */
public class Volumenejercicio extends javax.swing.JPanel {

    /**
     * Creates new form Volumenejercicio
     */
    public Volumenejercicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 230, 225));

        jLabel1.setFont(new java.awt.Font("Palatino Linotype", 1, 18)); // NOI18N
        jLabel1.setText("Ejercicios de figuras tridimensionales");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1144, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 50));

        jLabel2.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        jLabel2.setText("<html>1. Una caja de zapatos tiene dos caras cuyas dimensiones son 15 y 12 centímetros y el ancho es de 20 centímetros ¿Cuál es su volumen?<p><p>2. Una pirámide que tiene base rectangular, uno de los lados mide 4.5 metros, el otro mide 2.5 metros<p>y tiene 3 metros de altura ¿Cuál es su volumen?<p><p>3. Encontrar el área lateral y el área total de un prisma recto de 7.5 cm de alto, que tiene por base un pentágono cuyos lados miden 3 cm.<p><p>4. Hallar el volumen de un prisma triangular regular cuya base tiene 8 pulgadas de lado y la altura del prisma es igual a 17 pulgadas.<p><p>5. Hallar el volumen y total de un prisma de caras cuadradas cuya base tiene 2 cm. de lado y la altura<p>del prisma 12 cm.<p><p>6. Hallar el volumen total de un cubo si una de sus aristas mide 6 cm.<p><p>7. Hallar el volumen de una pirámide pentagonal regular cuya base tiene 3 cm de lado y la altura<p>mide 12 cm.<p><p>8. La altura de una pirámide hexagonal regular mide 24 m. y el lado de la base 10 m. Hallar su volumen.<p><p>9. Hallar el área lateral y total de un prisma hexagonal de caras cuadradas cuyo lado de la base mide 6 cm.<p>y de altura tiene 24 cm.<p><p>10.Calcule el área de una esfera de 25 cm. de radio. <html>");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 870, 800));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
