/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finalproyecto;

import static finalproyecto.Mathe.Principalpanel;
import java.awt.BorderLayout;

/**
 *
 * @author Sergio Orozco
 */
public class volumenes extends javax.swing.JPanel {

    /**
     * Creates new form volumenes
     */
    public volumenes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 230, 225));

        jLabel1.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        jLabel1.setText("Volumes de figuras tridimensionales");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1489, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 231, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1720, -1));

        jLabel2.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        jLabel2.setText("Prisma");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, -1, -1));

        jLabel4.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        jLabel4.setText("<html>Cuerpo geométrico cuyas<p>bases son dos polígonos<p> iguales y paralelos y sus caras laterales son paralelogramos<html>");
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 250, 180));

        jLabel5.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/rectangular-prism.png"))); // NOI18N
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 60, 100));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 280, 1500, 20));

        jLabel6.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        jLabel6.setText("<html>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<html>");
        jLabel6.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 50, 10, 230));

        jLabel7.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        jLabel7.setText("<html>Figura en donde las<p>tres dimensiones son<p>iguales.<html>");
        jLabel7.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, 200, 90));

        jLabel8.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        jLabel8.setText("Cubo");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 60, -1, -1));

        jLabel9.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/3d (2).png"))); // NOI18N
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 200, -1, -1));

        jLabel10.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        jLabel10.setText("<html>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<html>");
        jLabel10.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, 10, 840));

        jLabel11.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        jLabel11.setText("Piramide");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 60, -1, -1));

        jLabel12.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        jLabel12.setText("<html>Cuerpo geométrico cuya base es un<p>polígono cualquiera y sus caras laterales<p>triángulos<html>");
        jLabel12.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 90, 170, 130));

        jLabel13.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pyramid.png"))); // NOI18N
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 200, -1, -1));

        jLabel14.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        jLabel14.setText("<html>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<p>|<html>");
        jLabel14.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 50, 10, 830));

        jLabel15.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        jLabel15.setText("Cilindro");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 60, -1, -1));

        jLabel16.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        jLabel16.setText("<html>Es el Cuerpo geométrico engendrado por la revolución de un rectángulo alrededor de uno<p>de sus lados <html>");
        jLabel16.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 90, 270, 170));

        jLabel17.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cylinder (1).png"))); // NOI18N
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 190, -1, -1));

        jLabel18.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        jLabel18.setText("Fórmula");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, -1, -1));

        jLabel19.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        jLabel19.setText("V=(h)(aB)");
        add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, -1, -1));

        jLabel20.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        jLabel20.setText("Fórmula");
        add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 100, -1, -1));

        jLabel21.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        jLabel21.setText("V=a^3");
        add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 140, -1, -1));

        jLabel22.setText("a");
        add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 260, 10, -1));

        jLabel23.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        jLabel23.setText("Fórmula");
        add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 90, -1, -1));

        jLabel24.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        jLabel24.setText("V=(aB*h)/3");
        add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 120, -1, -1));

        jLabel25.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        jLabel25.setText("V=(h)(π)(r^2)");
        add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 130, -1, -1));

        jLabel26.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        jLabel26.setText("Fórmula");
        add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 100, -1, -1));

        jLabel3.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        jLabel3.setText("Cono");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, -1, -1));

        jLabel27.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        jLabel27.setText("<html>Es el Cuerpo geometrico engendrado por la revolución de un triángulo rectángulo alrededor de uno<html>");
        jLabel27.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 230, 140));

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cone.png"))); // NOI18N
        add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 450, -1, -1));

        jLabel29.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        jLabel29.setText("Fórmula");
        add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 350, -1, -1));

        jLabel30.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        jLabel30.setText("V=((h)(π)(r^2))/3");
        add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 390, -1, -1));

        jLabel31.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        jLabel31.setText("Esfera");
        add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 300, -1, -1));

        jLabel32.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        jLabel32.setText("<html>Cuerpo geometrico engendrado por la revolución completa de un semicírculo alrededor de su diámetro.<html>");
        jLabel32.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 330, 190, 130));

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/3d-printers.png"))); // NOI18N
        add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 500, -1, -1));

        jLabel34.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        jLabel34.setText("Octaedro");
        add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 300, 80, -1));

        jLabel35.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        jLabel35.setText("<html>es un poliedro de ocho caras. Con este número de caras puede ser un poliedro convexo o un poliedro cóncavo. Sus caras pueden ser polígonos de siete lados a lo más .<html>");
        jLabel35.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 330, 280, 180));

        jButton1.setText("Ejercicios");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1400, 790, -1, -1));

        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/octahedron.png"))); // NOI18N
        add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 370, -1, -1));

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/voluoct.png"))); // NOI18N
        add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 470, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         Volumenejercicio p=new Volumenejercicio();
        p.setSize(1643, 990);
        p.setLocation(15,0);
        Principalpanel.removeAll();
        Principalpanel.add(p,BorderLayout.CENTER);
        Principalpanel.revalidate();
        Principalpanel.repaint();
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
